drop schema practicaintegradora;
create schema practicaintegradora;

insert into genero(nombre, siglas) values ("Femenino", "F");
insert into genero(nombre, siglas) values ("Masculino", "M");
insert into genero(nombre, siglas) values ("No Binario", "N");
insert into genero(nombre, siglas) values ("Otro", "O");
insert into estado_pedido(nombre, siglas) values ("En preparacion", "P");
insert into estado_pedido(nombre, siglas) values ("En transito", "T");
insert into estado_pedido(nombre, siglas) values ("Extraviado", "X");
insert into estado_pedido(nombre, siglas) values ("Entregado", "E");
insert into tipo_documento_cliente(nombre, siglas) values ("DNI", "D");
insert into tipo_documento_cliente(nombre, siglas) values ("NIE", "N");
insert into tipo_documento_cliente(nombre, siglas) values ("Nº Pasaporte", "P");
insert into tipo_documento_cliente(nombre, siglas) values ("Nº Seguridad Social", "S");
insert into tipo_documento_proveedor(nombre, siglas) values ("CIF", "C");
insert into tipo_documento_proveedor(nombre, siglas) values ("DNI", "D");
insert into tipo_via(nombre, siglas) values ("Avenida", "Av");
insert into tipo_via(nombre, siglas) values ("Calle", "Cl");
insert into tipo_via(nombre, siglas) values ("Glorieta", "Gl");
insert into tipo_via(nombre, siglas) values ("Paseo", "Ps");
insert into tipo_via(nombre, siglas) values ("Plaza", "Pz");
insert into tipo_cliente(nombre, siglas, gasto_umbral, porcentaje_descuento) values ("Ninguno", "Na", 0, 0);
insert into tipo_cliente(nombre, siglas, gasto_umbral, porcentaje_descuento) values ("Bronce", "Br", 100, 5);
insert into tipo_cliente(nombre, siglas, gasto_umbral, porcentaje_descuento) values ("Plata", "Pl", 200, 10);
insert into tipo_cliente(nombre, siglas, gasto_umbral, porcentaje_descuento) values ("Oro", "O", 300, 15);
insert into tipo_cliente(nombre, siglas, gasto_umbral, porcentaje_descuento) values ("Platino", "Pt", 400, 20);
insert into clase_proveedor(nombre, siglas) values ("Básico", "B");
insert into clase_proveedor(nombre, siglas) values ("Prioritario", "P");
insert into clase_proveedor(nombre, siglas) values ("Esencial", "E");
insert into tipo_tarjeta_credito(nombre, siglas) values ("Master Card", "M");
insert into tipo_tarjeta_credito(nombre, siglas) values ("Visa", "V");
insert into tipo_tarjeta_credito(nombre, siglas) values ("American Express", "A");
insert into tamanio_imagen(nombre, siglas) values ("Pequeña", "P");
insert into tamanio_imagen(nombre, siglas) values ("Mediana", "M");
insert into tamanio_imagen(nombre, siglas) values ("Grande", "L");
insert into tamanio_imagen(nombre, siglas) values ("Extra Grande", "XL");
insert into formato_imagen(nombre, siglas) values ("gif", "g");
insert into formato_imagen(nombre, siglas) values ("png", "p");
insert into formato_imagen(nombre, siglas) values ("jpg", "j");
insert into formato_imagen(nombre, siglas) values ("svg", "s");
insert into urgencia_aviso(nombre, siglas) values ("Baja", "B");
insert into urgencia_aviso(nombre, siglas) values ("Media", "M");
insert into urgencia_aviso(nombre, siglas) values ("Alta", "A");
insert into punto_cardinal(nombre, siglas) values ("Norte", "N");
insert into punto_cardinal(nombre, siglas) values ("Sur", "S");
insert into punto_cardinal(nombre, siglas) values ("Este", "E");
insert into punto_cardinal(nombre, siglas) values ("Oeste", "O");
insert into pais(nombre, siglas) values ("España", "es");
insert into pais(nombre, siglas) values ("Francia", "fr");
insert into pais(nombre, siglas) values ("Italia", "it");
insert into pais(nombre, siglas) values ("Portugal", "pt");
insert into idioma(nombre, siglas) values ("Inglés", "en");
insert into idioma(nombre, siglas) values ("Español", "es");
insert into idioma(nombre, siglas) values ("Francés", "fr");

insert into categoria(codigo, descripcion) values ("1", "deporte");
insert into categoria(codigo, descripcion) values ("2", "musica");
insert into categoria(codigo, descripcion) values ("3", "cine");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("4", "futbol", "1");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("5", "pop", "2");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("6", "funk", "2");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("7", "fantasia", "3");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("8", "futbol europeo", "4");
insert into categoria(codigo, descripcion, categoria_padre_codigo) values ("9", "steampunk", "3");

insert into aviso(descripcion, urgencia_aviso, fecha_creacion) values ("prueba", "Alta", "2001-12-09");
